CREATE OR REPLACE WAREHOUSE ML_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;
CREATE DATABASE INSURANCE;
CREATE SCHEMA INSURANCE.ML_PIPE;
USE WAREHOUSE ML_WH;
USE DATABASE INSURANCE;
USE SCHEMA ML_PIPE;
SELECT CURRENT_WAREHOUSE(),
       CURRENT_DATABASE(),
       CURRENT_SCHEMA();
       USE WAREHOUSE ML_WH;
USE DATABASE INSURANCE;
USE SCHEMA ML_PIPE;

CREATE OR REPLACE TABLE INSURANCE_DATA (
    AGE NUMBER,
    SEX VARCHAR,
    BMI FLOAT,
    CHILDREN NUMBER,
    SMOKER VARCHAR,
    REGION VARCHAR,
    CHARGES FLOAT
);
INSERT INTO INSURANCE_DATA
SELECT
    UNIFORM(18, 65, RANDOM()) AS AGE,
    CASE WHEN UNIFORM(0, 2, RANDOM()) = 0 THEN 'male' ELSE 'female' END AS SEX,
    ROUND(18 + UNIFORM(0, 2300, RANDOM()) / 100.0, 2) AS BMI,
    UNIFORM(0, 5, RANDOM()) AS CHILDREN,
    CASE WHEN UNIFORM(0, 5, RANDOM()) = 0 THEN 'yes' ELSE 'no' END AS SMOKER,
    CASE UNIFORM(0, 4, RANDOM())
        WHEN 0 THEN 'southwest'
        WHEN 1 THEN 'southeast'
        WHEN 2 THEN 'northwest'
        ELSE 'northeast'
    END AS REGION,
    2000
      + AGE * 250
      + BMI * 300
      + CHILDREN * 500
      + CASE WHEN SMOKER = 'yes' THEN 20000 ELSE 0 END
      + UNIFORM(0, 5000, RANDOM()) AS CHARGES
FROM TABLE(GENERATOR(ROWCOUNT => 10000));
SELECT *
FROM INSURANCE_DATA
LIMIT 10;
SELECT COUNT(*) AS TOTAL_ROWS
FROM INSURANCE_DATA;
CREATE OR REPLACE TABLE INSURANCE_TRAIN AS
SELECT *
FROM INSURANCE_DATA
WHERE MOD(SEQ8(), 5) <> 0;
CREATE OR REPLACE TABLE INSURANCE_TEST AS
SELECT *
FROM INSURANCE_DATA
WHERE MOD(SEQ8(), 5) = 0;
USE DATABASE INSURANCE;
USE SCHEMA ML_PIPE;

SELECT *
FROM INSURANCE_PREDICTIONS
LIMIT 10;
SHOW MODELS IN SCHEMA INSURANCE.ML_PIPE;
SHOW VERSIONS IN MODEL INSURANCE.ML_PIPE.INSURANCE_CHARGE_MODEL;
SHOW VERSIONS IN MODEL INSURANCE.ML_PIPE.INSURANCE_CHARGE_MODEL;
SELECT COUNT(*) AS TRAIN_ROWS
FROM INSURANCE_TRAIN;

SELECT COUNT(*) AS TEST_ROWS
FROM INSURANCE_TEST;

SELECT *
FROM INSURANCE_PREDICTIONS
LIMIT 10;
CREATE OR REPLACE STREAM INSURANCE_PREDICTIONS_STREAM
ON TABLE INSURANCE_PREDICTIONS;
SHOW STREAMS;
CREATE OR REPLACE TABLE NEW_INSURANCE_CUSTOMERS (
    AGE NUMBER,
    SEX VARCHAR,
    BMI FLOAT,
    CHILDREN NUMBER,
    SMOKER VARCHAR,
    REGION VARCHAR
);
INSERT INTO NEW_INSURANCE_CUSTOMERS
VALUES
(32, 'female', 26.5, 1, 'no', 'southeast'),
(45, 'male', 31.2, 2, 'yes', 'southwest'),
(27, 'female', 23.8, 0, 'no', 'northeast'),
(51, 'male', 29.4, 3, 'no', 'northwest'),
(38, 'female', 35.1, 2, 'yes', 'southeast');
SELECT *
FROM NEW_INSURANCE_CUSTOMERS;
CREATE OR REPLACE TABLE NEW_INSURANCE_PREDICTIONS (
    AGE NUMBER,
    SEX VARCHAR,
    BMI FLOAT,
    CHILDREN NUMBER,
    SMOKER VARCHAR,
    REGION VARCHAR,
    PREDICTED_CHARGES FLOAT,
    PREDICTION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
